### Updates an existing patient entity
PUT http://localhost:4000/api/v1/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Michael Shaba",
  "email": "michaelsmith@outlook.com",
  "address": "23 Main St, Springfield, IL",
  "dateOfBirth": "1990-05-15"


}
###